version: '3'

services:
  app:
    env_file:
      - .env
    restart: always
    container_name: guarita-whatsapp-1
    build: .
    ports:
      - ${PORT}:${PORT}
    volumes:
      - node_modules_cache:/usr/app/node_modules
      - ./volumes:/usr/app/volumes
    environment:
      VIRTUAL_HOST: ${LETSENCRYPT_HOST}
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    working_dir: /usr/app
    # depends_on:
    #   - cache
    logging:
      driver: 'json-file'
      options:
        max-size: '8m'
        max-file: '3'
volumes:
  node_modules_cache:


networks:
  default:
    external: true
    name: database
