version: '3'

services:
  app:
    env_file:
      - .env
    restart: always
    container_name: guarita-whatsapp
    build: .
    ports:
      - ${PORT}:${PORT}
    volumes:
      - node_modules_cache:/usr/app/node_modules
      - ./volumes:/usr/app/volumes
    environment:
      VIRTUAL_HOST: ${LETSENCRYPT_HOST}
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    working_dir: /usr/app
    logging:
      driver: 'json-file'
      options:
        max-size: '8m'
        max-file: '3'
    deploy:
      resources:
        limits:
          memory: 254M
  cache:
    env_file:
      - .env
    image: redis:alpine
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - redis_data:/var/lib/redis
      - ./volumes/redis/redis.conf:/usr/local/etc/redis/redis.conf

volumes:
  node_modules_cache:

  redis_data:
    

# networks:
#   default:
#     external:
#       name: webproxy
